name: Puma Prey

on:
  workflow_dispatch:

permissions:
  actions: read # read gh actions
  contents: read # read access to the repo
  security-events: write # write access to advanced security

env:
  SOLUTION: "./PumaPrey.sln"
  CONFIGURATION: "Release"

jobs:
  build:
    name: Build Puma Prey
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialization
        shell: powershell
        run: |
          $MSBuildPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe" | Select-Object -first 1
          $MSBuildVersion = & $MSBuildPath -Version
          Write-Host "MSBuild version: "
          Write-Host "$MSBuildVersion"
          Write-Host "Nuget version: "
          nuget help
      - name: Build
        shell: powershell
        run: |
          $MSBuildPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe" | Select-Object -first 1  
          nuget restore ${{ env.SOLUTION }}
          & $MSBuildPath ${env.SOLUTION} /p:Configuration=${{ env.CONFIGURATION }}
